version: '3.7'
services:
  my-rabbit:
    tty: true
    image: rabbitmq:management-alpine
    hostname: my-rabbit
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"      
      - "15672:15672"
    volumes:
      - ${PWD}/certs:/cert_rabbitmq
      - ${PWD}/etc/:/etc/rabbitmq/